spring:
  application:
    name: Url Shorter
    version: 1.0
    author: Paulo Gabriel Justino Bezerra
    contact: contact@pgjbz.dev
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:url-shorter}
    username: ${PG_USER:url-shorter}
    password: ${PG_PASS:url-shorter}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        org.apache.kafka.common.serialization.StringSerializer

hashids:
  salt: ${ID_SALT:url-shorter}

ratelimit:
  timeout-duration: ${RATE_LIMIT_DURATION:500}
  refresh-period: ${RATE_LIMIT_REFRESH_PERIOD:100}
  requests-per-period: ${RATE_LIMIT_REQUESTS_PER_PERIOD:50}

url:
  host-name: ${URL_SHORTER_HOST_NAME:localhost}

management:
  health:
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 
        - prometheus
        - health
        - info