version: '3'

services:



  postgres:
    image: postgres:15-alpine
    environment:
    - POSTGRES_DB=url-shorter
    - POSTGRES_USER=url-shorter
    - POSTGRES_PASSWORD=url-shorter
    networks:
    - k6_tests

  application:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
    - PG_HOST=postgres
    - PG_PORT=5432
    - PG_DB=url-shorter
    - PG_USER=url-shorter
    - PG_PASS=url-shorter
    networks:
    - k6_tests
    depends_on:
    - postgres

  influxdb:
    image: influxdb:1.8
    networks:
    - k6_tests
    environment:
    - INFLUXDB_DB=k6
  
  grafana:
    image: grafana/grafana:latest
    networks:
    - k6_tests
    ports:
    - 3000:3000
    environment:
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_BASIC_ENABLED=false
    - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
    - ./dashboards:/var/lib/grafana/dashboards
    - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: docker.io/grafana/k6:0.41.0
    command: run --vus 100 --duration 60s /tmp/k6.js
    volumes:
    - ./k6.js:/tmp/k6.js
    environment:
    - HOST=application
    - K6_OUT=influxdb=http://influxdb:8086/k6
    networks:
    - k6_tests
    depends_on:
    - application
    - influxdb



networks:
  k6_tests: