version: '3'

services:

  postgres:
    image: postgres:15-alpine
    environment:
    - POSTGRES_DB=url-shorter
    - POSTGRES_USER=url-shorter
    - POSTGRES_PASSWORD=url-shorter
    ports:
    - 5432:5432
    networks:
    - app
  
  application:
    container_name: url-shorter
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
    - PG_HOST=postgres
    - PG_PORT=5432
    - PG_DB=url-shorter
    - PG_USER=url-shorter
    - PG_PASS=url-shorter
    - ID_SALT=ultramegablastpowerfullsalt
    ports:
    - "8080:8080"
    depends_on:
    - postgres
    networks:
    - app

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    volumes:
    - "./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yaml"
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
    - "9090:9090" 
    networks:
    - app


  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    environment:
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_BASIC_ENABLED=false
    - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
    - app
    


networks:
  app:
  