version: '3'

services:



  postgres:
    image: postgres:15-alpine
    environment:
    - POSTGRES_DB=url-shorter
    - POSTGRES_USER=url-shorter
    - POSTGRES_PASSWORD=url-shorter
    networks:
    - k6_tests

  application:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
    - PG_HOST=postgres
    - PG_PORT=5432
    - PG_DB=url-shorter
    - PG_USER=url-shorter
    - PG_PASS=url-shorter
    networks:
    - k6_tests
    depends_on:
    - postgres

  k6:
    image: docker.io/grafana/k6:0.41.0
    command: run --vus 100 --duration 60s /tmp/k6.js
    volumes:
    - ./k6.js:/tmp/k6.js
    environment:
    - HOST=application
    networks:
    - k6_tests
    depends_on:
    - application

networks:
  k6_tests: