version: '3'

services:

  postgres:
    image: postgres:15-alpine
    environment:
    - POSTGRES_DB=url-shorter
    - POSTGRES_USER=url-shorter
    - POSTGRES_PASSWORD=url-shorter
    ports:
    - 5432:5432
    networks:
    - app
  
  application:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
    - PG_HOST=postgres
    - PG_PORT=5432
    - PG_DB=url-shorter
    - PG_USER=url-shorter
    - PG_PASS=url-shorter
    - ID_SALT=ultramegablastpowerfullsalt
    ports:
    - "8080:8080"
    networks:
    - app
    depends_on:
    - postgres

networks:
  app:
  