spring:
  application:
    name: Url Shorter
    version: 1.0
    author: Paulo Gabriel Justino Bezerra
    contact: contact@pgjbz.dev
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:url-shorter}
    username: ${PG_USER:url-shorter}
    password: ${PG_PASS:url-shorter}

hashids:
  salt: ${ID_SALT:url-shorter}

ratelimit:
  timeout-duration: ${RATE_LIMIT_DURATION:500}
  refresh-period: ${RATE_LIMIT_REFRESH_PERIOD:100}
  requests-per-period: ${RATE_LIMIT_REQUESTS_PER_PERIOD:50}

management:
  health:
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 
        - prometheus
        - health
        - info