global:
  scrape_interval: 15s

  external_labels:
    monitor: 'url-monitor'


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets:
      - "localhost:9090"

  - job_name: 'url-shorter'
    metrics_path: /actuator/prometheus
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: 0
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    static_configs:
    - targets:
      # - "host.docker.internal:8080"
      - "application:8080"
